name: Unit Tests
on: 
  pull_request:
    branches: [ "master", "develop"]

jobs:
  unit_tests:
    name: Unit Tests - Coverage - MyPy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build -t oprl .

    - name: Ruff
      run: |
        docker run --rm oprl sh -c "
          uv run ruff check src
        "
    
    - name: Unit Tests
      run: docker run --rm oprl

    - name: MyPy
      run: |
        docker run --rm oprl sh -c "
          uv run mypy --ignore-missing-imports  --python-version 3.10 src/oprl/runners src/oprl/trainers src/opr/buffers
        "

    - name: Extract coverage
      run: |
        docker run --rm -v $(pwd):/host oprl sh -c "
          uv run pytest tests/functional --cov=oprl --cov-report=xml &&
          cp coverage.xml /host/
        "
    
    - name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: schatty/oprl
        file: ./coverage.xml
